/*
 * Copyright (c) 2018-2019 Pavel Kastornyy. All rights reserved.
 * The specified copyright does not cover application programming interface
 * (API) and the documentation for this API, which were taken from other
 * libraries. See NOTICE file for more information.
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation. Copyright holder designates
 * this particular file as subject to the "Classpath" exception as provided
 * by copyright holder in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 */

import { KeyCode } from './../../scene/input/KeyCode';

/**
 * Map from all codes from https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code
 */
export class HtmlKeyMapper {
    
    private static readonly keyCodesByHtmlKeys: Object = {
        AGAIN: KeyCode.AGAIN,
        ALTLEFT: KeyCode.ALT,
        ALTRIGHT: KeyCode.ALT,
        ARROWDOWN: KeyCode.DOWN,
        ARROWLEFT: KeyCode.LEFT,
        ARROWRIGHT: KeyCode.RIGHT,
        ARROWUP: KeyCode.UP,
        AUDIOVOLUMEDOWN: KeyCode.VOLUME_DOWN,
        AUDIOVOLUMEMUTE: KeyCode.MUTE,
        AUDIOVOLUMEUP: KeyCode.VOLUME_UP,
        BACKQUOTE: KeyCode.BACK_QUOTE,
        BACKSLASH: KeyCode.BACK_SLASH,
        BACKSPACE: KeyCode.BACK_SPACE,
//        BRACKETLEFT: KeyCode.,
//        BRACKETRIGHT: KeyCode.,
//        BROWSERBACK: KeyCode.,
//        BROWSERFAVORITES: KeyCode.,
//        BROWSERFORWARD: KeyCode.,
//        BROWSERHOME: KeyCode.,
//        BROWSERREFRESH: KeyCode.,
//        BROWSERSEARCH: KeyCode.,
//        BROWSERSTOP: KeyCode.,
        CANCEL: KeyCode.CANCEL,
        CAPSLOCK: KeyCode.CAPS,
        COMMA: KeyCode.COMMA,
        CONTEXTMENU: KeyCode.CONTEXT_MENU,
        CONTROLLEFT: KeyCode.CONTROL,
        CONTROLRIGHT: KeyCode.CONTROL,
        CONVERT: KeyCode.CONVERT,
        COPY: KeyCode.COPY,
        CUT: KeyCode.CUT,
        DELETE: KeyCode.DELETE,
        DIGIT0: KeyCode.DIGIT0,
        DIGIT1: KeyCode.DIGIT1,
        DIGIT2: KeyCode.DIGIT2,
        DIGIT3: KeyCode.DIGIT3,
        DIGIT4: KeyCode.DIGIT4,
        DIGIT5: KeyCode.DIGIT5,
        DIGIT6: KeyCode.DIGIT6,
        DIGIT7: KeyCode.DIGIT7,
        DIGIT8: KeyCode.DIGIT8,
        DIGIT9: KeyCode.DIGIT9,
        EJECT: KeyCode.EJECT_TOGGLE,
        END: KeyCode.END,
        ENTER: KeyCode.ENTER,
        EQUAL: KeyCode.EQUALS,
        ESCAPE: KeyCode.ESCAPE,
        F1: KeyCode.F1,
        F10: KeyCode.F10,
        F11: KeyCode.F11,
        F12: KeyCode.F12,
        F13: KeyCode.F13,
        F14: KeyCode.F14,
        F15: KeyCode.F15,
        F16: KeyCode.F16,
        F17: KeyCode.F17,
        F18: KeyCode.F18,
        F19: KeyCode.F19,
        F2: KeyCode.F2,
        F20: KeyCode.F20,
        F21: KeyCode.F21,
        F22: KeyCode.F22,
        F23: KeyCode.F23,
        F24: KeyCode.F24,
        F3: KeyCode.F3,
        F4: KeyCode.F4,
        F5: KeyCode.F5,
        F6: KeyCode.F6,
        F7: KeyCode.F7,
        F8: KeyCode.F8,
        F9: KeyCode.F9,
        FIND: KeyCode.FIND,
//        FN: KeyCode.,
//        HANGULMODE: KeyCode.,
//        HANJA: KeyCode.,
        HELP: KeyCode.HELP,
        HOME: KeyCode.HOME,
        INSERT: KeyCode.INSERT,
//        INTLBACKSLASH: KeyCode.,
//        INTLRO: KeyCode.,
//        INTLYEN: KeyCode.,
//        KANAMODE: KeyCode.,
        KEYA: KeyCode.A,
        KEYB: KeyCode.B,
        KEYC: KeyCode.C,
        KEYD: KeyCode.D,
        KEYE: KeyCode.E,
        KEYF: KeyCode.F,
        KEYG: KeyCode.G,
        KEYH: KeyCode.H,
        KEYI: KeyCode.I,
        KEYJ: KeyCode.J,
        KEYK: KeyCode.K,
        KEYL: KeyCode.L,
        KEYM: KeyCode.M,
        KEYN: KeyCode.N,
        KEYO: KeyCode.O,
        KEYP: KeyCode.P,
        KEYQ: KeyCode.Q,
        KEYR: KeyCode.R,
        KEYS: KeyCode.S,
        KEYT: KeyCode.T,
        KEYU: KeyCode.U,
        KEYV: KeyCode.V,
        KEYW: KeyCode.W,
        KEYX: KeyCode.X,
        KEYY: KeyCode.Y,
        KEYZ: KeyCode.Z,
//        LANG1: KeyCode.,
//        LANG2: KeyCode.,
//        LAUNCHAPP1: KeyCode.,
//        LAUNCHAPP2: KeyCode.,
//        LAUNCHMAIL: KeyCode.,
//        LAUNCHMEDIAPLAYER: KeyCode.,
//        MEDIAPLAYPAUSE: KeyCode.,
//        MEDIASELECT: KeyCode.,
//        MEDIASTOP: KeyCode.,
//        MEDIATRACKNEXT: KeyCode.,
//        MEDIATRACKPREVIOUS: KeyCode.,
        METALEFT: KeyCode.META,
        METARIGHT: KeyCode.META,
        MINUS: KeyCode.MINUS,
        NONCONVERT: KeyCode.NONCONVERT,
        NUMLOCK: KeyCode.NUM_LOCK,
        NUMPAD0: KeyCode.NUMPAD0,
        NUMPAD1: KeyCode.NUMPAD1,
        NUMPAD2: KeyCode.NUMPAD2,
        NUMPAD3: KeyCode.NUMPAD3,
        NUMPAD4: KeyCode.NUMPAD4,
        NUMPAD5: KeyCode.NUMPAD5,
        NUMPAD6: KeyCode.NUMPAD6,
        NUMPAD7: KeyCode.NUMPAD7,
        NUMPAD8: KeyCode.NUMPAD8,
        NUMPAD9: KeyCode.NUMPAD9,
        NUMPADADD: KeyCode.ADD,
//        NUMPADCHANGESIGN: KeyCode.,
        NUMPADCOMMA: KeyCode.COMMA,
        NUMPADDECIMAL: KeyCode.DECIMAL,
        NUMPADDIVIDE: KeyCode.DIVIDE,
        NUMPADENTER: KeyCode.ENTER,
        NUMPADEQUAL: KeyCode.EQUALS,
        NUMPADMULTIPLY: KeyCode.MULTIPLY,
//        NUMPADPARENLEFT: KeyCode.,
//        NUMPADPARENRIGHT: KeyCode.,
        NUMPADSUBTRACT: KeyCode.SUBTRACT,
//        OPEN: KeyCode.,
        OSLEFT: KeyCode.META,
        OSRIGHT: KeyCode.META,
        PAGEDOWN: KeyCode.PAGE_DOWN,
        PAGEUP: KeyCode.PAGE_UP,
        PASTE: KeyCode.PASTE,
        PAUSE: KeyCode.PAUSE,
        PERIOD: KeyCode.PERIOD,
        POWER: KeyCode.POWER,
        PRINTSCREEN: KeyCode.PRINTSCREEN,
        PROPS: KeyCode.PROPS,
        QUOTE: KeyCode.QUOTE,
        ROMANCHARACTERS: KeyCode.ROMAN_CHARACTERS,
        SCROLLLOCK: KeyCode.SCROLL_LOCK,
//        SELECT: KeyCode.,
        SEMICOLON: KeyCode.SEMICOLON,
        SHIFTLEFT: KeyCode.SHIFT,
        SHIFTRIGHT: KeyCode.SHIFT,
        SLASH: KeyCode.SLASH,
//        SLEEP: KeyCode.,
        SPACE: KeyCode.SPACE,
        TAB: KeyCode.TAB,
        UNDO: KeyCode.UNDO,
        VOLUMEDOWN: KeyCode.VOLUME_DOWN,
        VOLUMEMUTE: KeyCode.MUTE,
        VOLUMEUP: KeyCode.VOLUME_UP,
//        WAKEUP: KeyCode.,
    }
    
    public static map(htmlKey: string): KeyCode {
        return HtmlKeyMapper.keyCodesByHtmlKeys[htmlKey.toUpperCase()];
    }
}

